#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage: $0 <file>"
    exit 1
fi

filename=$1

while IFS= read -r number; do
    divisor=2

    while (( divisor < number )); do
        if (( number % divisor == 0 )); then
            quotient=$(( number / divisor ))
            echo "${number}=${quotient}*${divisor}"
            break
        fi
        divisor=$(( divisor + 1 ))
    done
done < "$filename"
