#!/bin/bash

# Function to check if a number is prime
is_prime() {
    if [ $1 -lt 2 ]; then
        return 1
    fi

    for ((i = 2; i * i <= $1; i++)); do
        if [ $((n % i)) -eq 0 ]; then
            return 1
        fi
    done

    return 0
}

# Check if an input file is provided
if [ -z "$1" ]; then
    echo "Usage: ./rsa <input_file>"
    exit 1
fi

# Read the input file
filename="$1"
n=$(cat "$filename")

# Find the prime factors of n
for ((i = 2; i * i <= $n; i++)); do
    if [ $((n % i)) -eq 0 ]; then
        factor1=$i
        factor2=$((n / i))
        break
    fi
done

# Check if both factors are prime
if is_prime $factor1 && is_prime $factor2; then
    echo "$n=$factor1*$factor2"
else
    echo "Unable to find prime factors for n: $n"
fi
